openapi: 3.0.0
info:
  title: Banking System
  description: >-
    **Banking System APIs**
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: >-
      ### **1\. Authentication Routes**
  - name: Users
    description: >-
      ### **2\. User Routes**
  - name: Branches
    description: >-
      ### **3\. Branch Routes**
  - name: Policies
    description: >-
      ### **4\. Policies Routes**
  - name: Accounts
    description: >-
      ### **5\. Account Management Routes**
  - name: Accounts > Transactions
    description: >-
      ### **6\. Transaction Routes**
  - name: Applications
    description: >-
      ### **7\. Application Routes**
  - name: Lockers
    description: >-
      ### **8\. Locker Management Routes**
  - name: Deposits
    description: >-
      ### **9\. Deposit Routes**
paths:
  /auth/otp-login:
    post:
      tags:
        - Auth
      summary: login user with otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: lakshyakumarsingh2621@gmail.com
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/otp-verify:
    post:
      tags:
        - Auth
      summary: verify user's otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: '{{EMAIL}}'
                otp: '988907'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/logout:
    delete:
      tags:
        - Auth
      summary: logout user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/register:
    post:
      tags:
        - Auth
      summary: register a new customer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Lakshya Kr. Singh
                email:
                  type: string
                  example: lakshyasingh23@gmail.com
                password:
                  type: integer
                  example: '876543653'
                contact:
                  type: integer
                  example: '1234567890'
                govIssueIdType:
                  type: string
                  example: adhar
                govIssueIdImage:
                  type: string
                  format: binary
                fatherName:
                  type: string
                  example: Randhir Kr. Singh
                motherName:
                  type: string
                  example: Ragini Singh
                address:
                  type: string
                  example: Kolkata, India
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/verify-email:
    post:
      tags:
        - Auth
      summary: verify email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: lakshyasingh23@gmail.com
                otp: '992615'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/otp-resend:
    post:
      tags:
        - Auth
      summary: resend otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: lakshyasingh23@gmail.com
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    post:
      tags:
        - Users
      summary: create user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Jyoti
                email:
                  type: string
                  example: lakshyarajput65@gmail.com
                password:
                  type: integer
                  example: '12345675'
                contact:
                  type: integer
                  example: '1214121121'
                govIssueIdType:
                  type: string
                  example: adhar
                govIssueIdImage:
                  type: string
                  format: binary
                fatherName:
                  type: string
                  example: Vasudev Purohit
                motherName:
                  type: string
                  example: Chanda Purohit
                address:
                  type: string
                  example: Udaipur
                isVerified:
                  type: boolean
                  example: 'true'
                roleCode:
                  type: integer
                  example: '102'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Users
      summary: index users
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: userRole
          in: query
          schema:
            type: integer
          example: '102'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}:
    get:
      tags:
        - Users
      summary: view user
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e66524db-81e6-4dd8-b78a-aa17932f3f5f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Users
      summary: update user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Aloy
                email: lakshyarajput26@gmail.com
                contact: '1211511121'
                fatherName: Rama
                motherName: Maya
                address: Kolkata India
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 690283c0-6486-427a-8638-23123d64b878
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Users
      summary: delete user
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 086e7b0a-bc58-4b5c-984f-ae37396b0615
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/me:
    get:
      tags:
        - Users
      summary: view me
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}/roles:
    patch:
      tags:
        - Users
      summary: assign new role to exisiting user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                rolesToAdd:
                  - '102'
                  - '103'
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: ef804641-1dbf-49cd-ba64-2e43329cc363
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /branches:
    post:
      tags:
        - Branches
      summary: create branch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                branchManagerId: e66524db-81e6-4dd8-b78a-aa17932f3f5f
                address: Orissa India
                ifscCode: k01342450
                contact: 1800 401 202
                totalLockers: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Branches
      summary: index branches
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /branches/{id}:
    get:
      tags:
        - Branches
      summary: view branch
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 78fcb217-5075-44d7-85d0-da57b3cbab14
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Branches
      summary: update branch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                address: Kolkata, India
                totalLockers: 14
                ifscCode: k76542345
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 78fcb217-5075-44d7-85d0-da57b3cbab14
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /policies:
    post:
      tags:
        - Policies
      summary: create policy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountType: savings
                initialAmount: 1000
                interestRate: 5
                minimumAmount: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Policies
      summary: index policies
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /policies/{id}:
    get:
      tags:
        - Policies
      summary: view policy
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e3f8ea87-dd89-4fc1-a97d-c81e67332274
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Policies
      summary: update policy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                interestRate: 6
                penaltyFee: 100
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e3f8ea87-dd89-4fc1-a97d-c81e67332274
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Policies
      summary: delete policy
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e3f8ea87-dd89-4fc1-a97d-c81e67332274
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /accounts/{accountId}/transactions:
    post:
      tags:
        - Accounts > Transactions
      summary: create transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountNo: '2530012137351437'
                type: transfer
                paymentMethod: UPI
                amount: 1000
      parameters:
        - name: accountId
          in: path
          schema:
            type: string
          required: true
          example: 62e03094-397f-4e31-b068-cdd0a5ca231b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Accounts > Transactions
      summary: index transactions
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: accountId
          in: path
          schema:
            type: string
          required: true
          example: 62e03094-397f-4e31-b068-cdd0a5ca231b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Accounts > Transactions
      summary: view transaction
      parameters:
        - name: accountId
          in: path
          schema:
            type: string
          required: true
          example: 62e03094-397f-4e31-b068-cdd0a5ca231b
        - name: transactionId
          in: path
          schema:
            type: string
          required: true
          example: d5595f34-85d8-43ea-a892-e6978142c61e
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /accounts:
    post:
      tags:
        - Accounts
      summary: create account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userId: e66524db-81e6-4dd8-b78a-aa17932f3f5f
                type: current
                nominee: Raja
                branchIfscCode: k01342456
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Accounts
      summary: index accounts
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: ifscCode
          in: query
          schema:
            type: string
          example: k01342456
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /accounts/{id}:
    get:
      tags:
        - Accounts
      summary: view account
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 5ed5eb02-2a06-48f6-b778-3c74e8f6ac83
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Accounts
      summary: update account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nominee: Mayya
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 5ed5eb02-2a06-48f6-b778-3c74e8f6ac83
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Accounts
      summary: delete account
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 3964f2d1-2173-4fd0-8ce0-ab7789c6ca0c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /applications/accounts:
    post:
      tags:
        - Applications
      summary: request account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                branchIfscCode: k01342456
                type: savings
                nomineeName: Ram
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /applications/lockers:
    post:
      tags:
        - Applications
      summary: request locker
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: locker
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /applications:
    get:
      tags:
        - Applications
      summary: list applications
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: requestType
          in: query
          schema:
            type: string
          example: lockers
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /applications/{id}:
    get:
      tags:
        - Applications
      summary: list application by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: d499a52f-8916-41c6-964c-865cbfe23ea7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lockers/assign:
    post:
      tags:
        - Lockers
      summary: assign a locker
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: lakshyarajput25@gmail.com
                lockerSerialNo: '6'
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: k01342456
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lockers:
    post:
      tags:
        - Lockers
      summary: create locker
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                numberOfLockers: 10
                monthlyCharge: 1500
                branchIfscCode: k01342450
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Lockers
      summary: index lockers
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lockers/{id}:
    get:
      tags:
        - Lockers
      summary: view locker
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 5f183a4a-24e1-4c7a-b6ae-f44fdc665fdc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Lockers
      summary: update locker
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                monthlyCharge: 1600
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 3fbda4e0-6c95-42ad-bd25-50952ba5d187
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Lockers
      summary: deallocate locker
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: dc77c525-d4dc-4346-91b6-8142fd54004c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /deposits:
    post:
      tags:
        - Deposits
      summary: create a deposit account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: fixed
                nominee: Rama
                principleAmount: 200000
      parameters:
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}